// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using costadelsoltapas.Models;

namespace costadelsoltapas.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("costadelsoltapas.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Classic",
                            Description = "From the good ol' grandma's recipes book. This tapas continue to stand the test of time, just as granny does."
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Fusion",
                            Description = "From the chef's imagination to your table. The best combinations are sometimes the weidest. Dare to try?"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Gourmet",
                            Description = "Carefully curated selection of Tapas for the more educated palate."
                        });
                });

            modelBuilder.Entity("costadelsoltapas.Models.Tapas", b =>
                {
                    b.Property<int>("TapasID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AllergyInformation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("ImageThumbnailUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("InStock")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTapasOfTheWeek")
                        .HasColumnType("bit");

                    b.Property<string>("LongDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ShortDescription")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TapasID");

                    b.HasIndex("CategoryId");

                    b.ToTable("Tapas");

                    b.HasData(
                        new
                        {
                            TapasID = 1,
                            AllergyInformation = "",
                            CategoryId = 1,
                            ImageThumbnailUrl = "https://lacocinadefrabisa.lavozdegalicia.es/wp-content/uploads/2019/05/tortilla-española.jpg",
                            ImageUrl = "https://lacocinadefrabisa.lavozdegalicia.es/wp-content/uploads/2019/05/tortilla-española.jpg",
                            InStock = true,
                            IsTapasOfTheWeek = false,
                            LongDescription = " The absolute classic. Found everywhere in Spain, it is not hard to see why this is an staple tapa in a culture where the quality of food is of upmost importance.",
                            Name = "Tortilla de Patatas",
                            Price = 5.95m,
                            ShortDescription = "Simple yet delicious."
                        },
                        new
                        {
                            TapasID = 2,
                            CategoryId = 1,
                            ImageThumbnailUrl = "http://www.importdelicia.com/contenido/noticias/600_img_36.jpg",
                            ImageUrl = "http://www.importdelicia.com/contenido/noticias/600_img_36.jpg",
                            InStock = true,
                            IsTapasOfTheWeek = false,
                            LongDescription = "Bite sized croquettes filled with the best Jamon and gently fried in olive oil.",
                            Name = "Croquetas del Dia",
                            Price = 8.95m,
                            ShortDescription = "Delicate confection, strong flavor!"
                        },
                        new
                        {
                            TapasID = 3,
                            CategoryId = 1,
                            ImageThumbnailUrl = "http://porsolea.com/wp-content/uploads/2017/04/pulpo-a-la-gallega-2.jpg",
                            ImageUrl = "http://porsolea.com/wp-content/uploads/2017/04/pulpo-a-la-gallega-2.jpg",
                            InStock = true,
                            IsTapasOfTheWeek = true,
                            LongDescription = "Despite being originally from the northern regions of Spain, this traditional Galician octopus dish is a star of the spanish cuisine.",
                            Name = "Polbo a Feira",
                            Price = 12.95m,
                            ShortDescription = "Lets see what Paul the octopus has to say."
                        },
                        new
                        {
                            TapasID = 4,
                            CategoryId = 2,
                            ImageThumbnailUrl = "https://jamonesjuanpedrodomecq.com/wp-content/uploads/2019/05/Tapas-españolas.jpg",
                            ImageUrl = "https://jamonesjuanpedrodomecq.com/wp-content/uploads/2019/05/Tapas-españolas.jpg",
                            InStock = true,
                            IsTapasOfTheWeek = true,
                            LongDescription = "Handmade bread, toasted and crowned with the best toppings choosed by the chef according with the current season.",
                            Name = "Tostas Costa del Sol",
                            Price = 20.95m,
                            ShortDescription = "The most versatile tapas made with the best ingredients, all year long."
                        },
                        new
                        {
                            TapasID = 5,
                            CategoryId = 3,
                            ImageThumbnailUrl = "https://www.ibericosguillen.com/tienda/wp-content/uploads/2018/10/Jamon-iberico-bellota-50-Guillen-1-1.jpg",
                            ImageUrl = "https://www.ibericosguillen.com/tienda/wp-content/uploads/2018/10/Jamon-iberico-bellota-50-Guillen-1-1.jpg",
                            InStock = true,
                            IsTapasOfTheWeek = true,
                            LongDescription = "The best Jamon Iberico 100% Bellota carefully sliced and presented by an expert of the craft. The best of the best. The Ballon d'Or of the Tapas. ",
                            Name = "Jamon Iberico",
                            Price = 20.95m,
                            ShortDescription = "A tapa you will not forget."
                        });
                });

            modelBuilder.Entity("costadelsoltapas.Models.Tapas", b =>
                {
                    b.HasOne("costadelsoltapas.Models.Category", "Category")
                        .WithMany("Tapas")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
